### ISSUE TITLE
Generation of readthedocs with mkdocs does not work anymore

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/dsol#28]
Changes in configuration for readthedocs.io results in a failure when generating documentation.

**Comment by averbraeck** [comment]
For readthedocs, a new file called `.readthedocs.yaml` in the root directory of the project is needed, with the following content:

```yaml
# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt
```
