### ISSUE TITLE
Github workflow: test if site building works

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/dsol#30]
There are a javadoc errors in spite of committing a new version... They are **not caught** when we deploy a version with github actions. This is, of course, wrong... Therefore, the github actions should try to build a site:

```yaml
    - name: Build with Maven and check if site building works
      run: mvn clean site --file pom.xml

    - name: Build with Maven and test if signing works
      run: mvn clean package -P release --file pom.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
```
